name: Reusable Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      domain:
        required: true
        type: string
      vite_react_app_auth0_domain:
        required: true
        type: string
      vite_react_app_auth0_client_id:
        required: true
        type: string
      vite_react_app_auth0_audience:
        required: true
        type: string
      vite_react_app_mermaid_dashboard_link:
        required: true
        type: string
      vite_react_app_mermaid_api_endcpoint:
        required: true
        type: string
      

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

      - if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
        name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn run build
        env:
          VITE_REACT_APP_AUTH0_DOMAIN: ${{ inputs.vite_react_app_auth0_domain }}
          VITE_REACT_APP_AUTH0_CLIENT_ID: ${{ inputs.vite_react_app_auth0_client_id }}
          VITE_REACT_APP_AUTH0_AUDIENCE: ${{ inputs.vite_react_app_auth0_audience }}
          VITE_REACT_APP_MERMAID_DASHBOARD_LINK: ${{ inputs.vite_react_app_mermaid_dashboard_link }}
          VITE_REACT_APP_MERMAID_API_ENDPOINT: ${{ inputs.vite_react_app_mermaid_api_endcpoint }}
          
      - name: Deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: deploy
          cdk_args: --require-approval never
          actions_comment: true
          working_dir: iac
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.CDK_DEFAULT_REGION }}
          CDK_DEFAULT_REGION: ${{ secrets.CDK_DEFAULT_REGION }}
          CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
          GITHUB_TOKEN: ${{ github.token }}
          ENV: ${{ inputs.environment }}
          DOMAIN: ${{ inputs.domain }}
