name: Deploy

on:
  push:
    branches:
      - develop
    tags:
      - 'v*.*.*'
jobs:
  deploy_develop:
    if: startsWith(github.ref, 'refs/heads/develop')
    uses: ./.github/workflows/_deploy.yml
    secrets: inherit
    with:
      environment: dev
      domain: dev-explore.datamermaid.org
      vite_react_app_auth0_domain: datamermaid.auth0.com
      vite_react_app_auth0_client_id: Yahf5mGpQDyYOqbvQlaKE1WqBnUeFPj0
      vite_react_app_auth0_audience: https://api.datamermaid.org
      vite_react_app_mermaid_dashboard_link: https://app.datamermaid.org
      vite_react_app_mermaid_api_endcpoint: https://api.datamermaid.org/v1/projectsummarysampleevents
      vite_react_app_map_tiler_api_key: L62nVuVTVPFCfHQKVqVk

  deploy_production:
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/_deploy.yml
    secrets: inherit
    with:
      environment: prod
      domain: explore.datamermaid.org
      vite_react_app_auth0_domain: datamermaid.auth0.com
      vite_react_app_auth0_client_id: Yahf5mGpQDyYOqbvQlaKE1WqBnUeFPj0
      vite_react_app_auth0_audience: https://api.datamermaid.org
      vite_react_app_mermaid_dashboard_link: https://app.datamermaid.org
      vite_react_app_mermaid_api_endcpoint: https://api.datamermaid.org/v1/projectsummarysampleevents
      vite_react_app_map_tiler_api_key: L62nVuVTVPFCfHQKVqVk
