name: Deploy

on:
  push:
    branches:
      - develop
    tags:
      - "v*.*.*"
jobs:
  deploy_develop:
    if: github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: dev
      domain: dev.dashboard3.datamermaid.org

  deploy_production:
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: prod
      domain: dashboard3.datamermaid.org
